package com.jlpay.appdelegate_apt.util;

//常量类
public final class Constants {
    //日志打印tag
    public static final String TAG_LOGGER = "->delegate>";
    //模块gradle文件中配置的参数的key,注解处理器可以根据这个key获取对应的值
    public static final String KEY_COMPONENT_NAME = "DELEGATE_COMPONENT_NAME";
    //@ModuleComponent注解的全路径名称
    public static final String ANNOTATION_MODULECOMPONENT = "com.jlpay.delegate.anontation.ModuleComponent";
    //IAppLifecycleDelegate接口的路径
    public static final String IAPPLIFECYCLEDELEGATE = "com.jeremy.appdelegate.IAppLifecycleDelegate";
    //DelegateMeta类的路径
    public static final String DELEGATEMETA = "com.jeremy.appdelegate.DelegateMeta";
    //生成类文件的包名
    public static final String PACKAGE_OF_GENERATE_APPDELEGATE_FILE = "com.jlpay.appdelegate.template";
    public static final String SEPARATOR = "$$";
    //生成类 类名的前缀
    public static final String MODULE_NAME_PREFIX = "Jlpay" + SEPARATOR;
    //生成类 类名的后缀
    public static final String MODULE_NAME_SUFFIX = SEPARATOR + "AppDelegate";

    //    public static final String WARN_TIPS_DOC = "";
    public static final String WARN_TIPS_DOC = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY applifecycle_delegate.\n" +
            "@author Hele 190610420@qq.com\n" +
            "@version 1.0";

    public static final String ILIFEDELEGATEGROUP = "com.jeremy.appdelegate.ILifeDelegateGroup";
}
